paths = [
    "purgepack",
    "test_module",
    "huffman_module",
    "rls_module",
    "delta_module",
]

[alias]
b = "build"
c = "check"
t = "test"
r = "run"
rr = "run --release"
recursive_example = "rr --example recursions"
space_example = ["run", "--release", "--", "\"command list\""]

[build]
target-dir = "target"
